import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createClient } from "@/utils/supabase/server";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "la cuillère",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const API_KEY = process.env.NEXT_PUBLIC_TINY_MCE_KEY!;

  return (
    <html lang="en" data-theme="cupcake">
      <head>
        <script
          src={`https://cdn.tiny.cloud/1/${API_KEY}/tinymce/8/tinymce.min.js`}
          referrerPolicy="origin"
          crossOrigin="anonymous"
        ></script>
        <script type="text/javascript">
  </script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
